# Author: Стурейко Игорь
## Project: Geekbrains.Linalg
## Lesson 02 - Матрицы
## Date: 2020-08-05

In [21]:
from numpy import array, dot, zeros
from numpy.linalg import det, matrix_rank

## 1.1. Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

### Решение:
Для перемножения необходимо, что бы число столбцов матрицы A было равно числу строк матрицы B

    a) BxA - не определено, AxB - не определено
    
    б) AxB - определено, BxA - не определено
    
    в) оба определены
    
    г) оба определены

## 1.2. Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

### Решение:

Сумма $A + B = \begin{pmatrix}
1+4 & -2+(-1)\\ 
3+0 & 0+5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

Произведение $A x B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} x \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1\cdot 4 + (-2)\cdot 0 & (1)\cdot(-1) + (-2)\cdot 5\\ 
3\cdot 4 + 0\cdot 0 & 3\cdot(-1) + 0\cdot 5
\end{pmatrix} = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [7]:
A = array([[1, -2], [3, 0]])
B = array([[4, -1],[0, 5]])
print(f'Сумма матриц: \n{A+B}')
print(f'Произведение матриц: \n{dot(A, B)}')

Сумма матриц: 
[[ 5 -3]
 [ 3  5]]
Произведение матриц: 
[[  4 -11]
 [ 12  -3]]


## 1.3. Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

### Решение:

$\displaystyle 3𝐴−2𝐵+4𝐶 = 3\cdot \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2 \cdot \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4\cdot \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} - \begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [8]:
A = array([[1, 7], [3, -6]])
B = array([[0, 5], [2, -1]])
C = array([[2, -4], [1, 1]])
3*A-2*B+4*C

array([[ 11,  -5],
       [  9, -12]])

$\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} - \begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$

## 1.4. Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

### Решение:

$\displaystyle A^T = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$

$\displaystyle AA^T = \begin{pmatrix}
4\cdot 4 + 1\cdot 1 & 4\cdot 5 + 1\cdot (-2) & 4\cdot 2 + 1\cdot 3\\ 
5\cdot 4 + (-2)\cdot 1 & 5\cdot 5 + (-2)\cdot (-2) & 5\cdot 2 + (-2)\cdot 3\\
2\cdot 4 + 3\cdot 1 & 2\cdot 5+3\cdot (-2) & 2\cdot 2 + 3\cdot 3
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}$

$\displaystyle A^TA = \begin{pmatrix}
4\cdot 4 + 5\cdot 5 + 2\cdot 2 & 4\cdot 1 + 5\cdot (-2) + 2\cdot 3 \\ 
1\cdot 4 + (-2)\cdot 5 + 3\cdot 2 & 1\cdot 1 + (-2)\cdot (-2) + 3\cdot 3 
\end{pmatrix} = \begin{pmatrix}
45 & 0 \\ 
0 & 14
\end{pmatrix}$

In [9]:
A = array([[4, 1], [5, -2], [2, 3]])
dot(A, A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [10]:
dot(A.T, A)

array([[45,  0],
       [ 0, 14]])

## 1.5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [19]:
def multiple (A, B):
    C = zeros((A.shape[0], B.shape[1])) 
    for i in range(A.shape[0]): 
        for j in range(B.shape[1]): 
            for k in range(A.shape[1]):  
                C[i, j]+=A[i, k]*B[k, j]
    return C

In [22]:
A = array([[4, 1], [5, -2], [2, 3]])
B = A.T
dot(A, B)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [23]:
multiple(A, B)

array([[17., 18., 11.],
       [18., 29.,  4.],
       [11.,  4., 13.]])

## 2.1. Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

### Решение:

a) $\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = \sin{x}^2 + \cos{x}^2 = 1$

б) $\displaystyle \begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4\cdot \begin{vmatrix} 
5 & 1\\ 
0 & 9
\end{vmatrix} - 0\cdot \begin{vmatrix} 
2 & 3\\ 
0 & 9
\end{vmatrix} + 0\cdot \begin{vmatrix} 
2 & 3\\ 
5 & 1
\end{vmatrix} = 4\cdot 5\cdot 9 = 180$

в) $\displaystyle \begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1\cdot \begin{vmatrix} 
5 & 6\\ 
8 & 9
\end{vmatrix} - 2\cdot \begin{vmatrix} 
4 & 6\\ 
7 & 9
\end{vmatrix} + 3\cdot \begin{vmatrix} 
4 & 5\\ 
7 & 8
\end{vmatrix} = 5\cdot9-6\cdot8 -2\cdot(4\cdot9-6\cdot7) + 3\cdot(4\cdot8-5\cdot7) = 45-48 - 2\cdot(36-42)+3\cdot(32-35)=-3 + 12  -9 = 0$

In [55]:
A = array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Определитель A: {det(A):.0f}')

Определитель A: 180


In [54]:
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Определитель A: {det(A):.0f}')

Определитель A: -0


## 2.2. Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

### Решение:

a) $\det(A^2) = \det(A)^{rank(A)}$

б) $\det(A^T) = 4$ по свойству определителя

в) $\det(2A) = 2^{rank(A)}\cdot\det(A)$

## 2.3.  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

### Решение:

$a_{1i}=a_{2i}\cdot(-1/2)$, определитель матрицы с линейнозависимыми строками = 0 $\Rightarrow$ матрица вырожденная

## 2.4. Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

### Решение:

a) $a_{1i}+a_{2i}=a_{3i} \\ $ где-то есть еще зависимость - пока не увидел

б) $a_{1i}+a_{2i}=a_{3i}$, больше линейнозависисых строк нет $\Rightarrow$ ранг = 3

In [43]:
A = array([[1, 2, 3], [1, 1, 1], 2, 3, 4])
matrix_rank(A)

1

In [65]:
A = array([[0, 0, 2, 1], [0, 0, 2, 2],[0, 0, 4, 3],[2, 3, 5, 6]])
matrix_rank(A)

3