# Author: Стурейко Игорь
## Project: Geekbrains.Linalg
## Lesson 03 - Системы линейных уравнений
## Date: 2020-08-11

## 1.1.Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

### Решение:

Расширенная матрица системы: $ \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

Умножим первую стороку на 2:
$\begin{pmatrix}
\left.\begin{matrix}
2 & 2 & -2 & -4\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

Вычтем из второй строки первую:
$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & 1 & 3 & 5\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
2\\
4
\end{matrix}
\end{pmatrix}$

Вычтем из третьей строки первую: $\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & 1 & 3 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
2\\
4
\end{matrix}
\end{pmatrix}$

$\begin{cases} 
\displaystyle x_3 = \frac{3x_4-4}{2},\\
\displaystyle x_2 = 2 - 5x_4 - \frac{3}{2}(3x_4-4), \\
\displaystyle x_1 = 2x_4 + \frac{3x_4-4}{2} - 2 + 5x_4 + \frac{3}{2}(3x_4-4)
\end{cases},$ где $x_4$ - любое 

## 1.2. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

### Решение:

Согласоно теореме Кронекера-Капелли Необходимым и достаточным условием совместности системы из $m$ уравнений с $n$ неизвестными является равенство между собой рангов матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$<br>
Причем:
- если $rankA=rank \tilde A=n$, где $n$ — число неизвестных, то система определена, т. е. имеет единственное решение;<br>
- если $rankA=rank \tilde A<n$, то система имеет бесконечное количество решений;<br>
- если $rankA<rank \tilde A$, то система несовместна.

In [1]:
import numpy as np
from numpy import linalg

In [140]:
def sovmest(A, A_w):
    if linalg.matrix_rank(A) == linalg.matrix_rank(A_w):
        if linalg.matrix_rank(A) == A.shape[1]:
            print(f'Система совместна и имеет единственное решение')
        elif linalg.matrix_rank(A) < A.shape[1]:
            print(f'Система совместна и имеет бесконечное число решений') 
    elif linalg.matrix_rank(A) < linalg.matrix_rank(A_w):
        print(f'Система несовместна, решений нет')

#### Вариант а)

In [141]:
A = np.array([[3, -1, 1],[2, -5, -3], [1, 1, -1]])
A_w = np.append(A, np.array([[4],[-17], [0]]), axis=1)
sovmest(A, A_w)

Система совместна и имеет единственное решение


#### Вариант б)

In [142]:
A = np.array([[2, -4, 6],[1, -2, 3], [3, -6, 9]])
A_w = np.append(A, np.array([[1],[-2], [5]]), axis=1)
sovmest(A, A_w)

Система несовместна, решений нет


#### Вариант в)

In [143]:
A = np.array([[1, 2, 5],[3, 1, -8]])
A_w = np.append(A, np.array([[4],[-2]]), axis=1)
sovmest(A, A_w)

Система совместна и имеет бесконечное число решений


## 1.3. Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

### Решение:

In [144]:
A = np.array([[1, 3, -2, 4],[0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
A_w = np.append(A, np.array([[3],[2],[4],[1]]), axis=1)
sovmest(A, A_w)

Система совместна и имеет единственное решение


## 1.4. Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

### Решение:

Для матрицы А: $a_2-a_1 = \begin{pmatrix}
3 & 3 & 3
\end{pmatrix}$ и $a_3-a_2 = \begin{pmatrix}
3 & 3 & 3
\end{pmatrix}$, следовательно достаточно, что бы $c- b \neq 3$ и $b-a \neq 3$, тогда ранг расширенной матрицы будет больше матрицы коэффицентов, что является условием несовместности по теореме Кронекера-Капелли.

## 2.1. Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

### Решение:

#### Вариант а)

In [136]:
A = np.array([[1, -2,],[3, -4]])
s = np.array([[1, 7]])

A_1 = np.copy(A)
A_1[::,0] = s

A_2 = np.copy(A)
A_2[::,1] = s

x1 = round(linalg.det(A_1)/linalg.det(A), 4)
x2 = round(linalg.det(A_2)/linalg.det(A), 4)
print(f'Решение системы: \nx1 = {x1}, \nx2 = {x2}')

Решение системы: 
x1 = 5.0, 
x2 = 2.0


#### Вариант б)

In [135]:
A = np.array([[2, -1, 5],[1, 1, -3], [2, 4, 1]])
s = np.array([[10, -2, 1]])

A_1 = np.copy(A)
A_1[::,0] = s

A_2 = np.copy(A)
A_2[::,1] = s

A_3 = np.copy(A)
A_3[::,2] = s

x1 = round(linalg.det(A_1)/linalg.det(A), 4)
x2 = round(linalg.det(A_2)/linalg.det(A), 4)
x3 = round(linalg.det(A_3)/linalg.det(A), 4)
print(f'Решение системы: \nx1 = {x1}, \nx2 = {x2}, \nx3 = {x3}')

Решение системы: 
x1 = 2.0, 
x2 = -1.0, 
x3 = 1.0


## 2.2*. Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

### Решение:

In [66]:
import scipy.linalg as la

In [101]:
def printMatrix ( matrix ): 
    for i in range ( len(matrix) ): 
        print('[', end='')
        for j in range ( len(matrix[i]) ): 
            print ("""{:7.2f}""".format(matrix[i][j]), end = "" ) 
        print(']\n')
    print ()

#### Вариант а)

In [132]:
a = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
(P, L, U) = la.lu(a)
print('LU разложение:\n')
print('Матрица L:')
printMatrix(L)
print('Матрица U:')
printMatrix(U)

LU разложение:

Матрица L:
[   1.00   0.00   0.00]

[   0.67   1.00   0.00]

[   0.33   0.80   1.00]


Матрица U:
[   3.00  26.00  30.00]

[   0.00  -8.33  -8.00]

[   0.00   0.00   0.40]




#### Вариант б)

In [131]:
a = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
(P, L, U) = la.lu(a)
print('LU разложение:\n')
print('Матрица L:')
printMatrix(L)
print('Матрица U:')
printMatrix(U)

LU разложение:

Матрица L:
[   1.00   0.00   0.00   0.00]

[   0.50   1.00   0.00   0.00]

[   0.75  -0.25   1.00   0.00]

[   0.25   0.75  -0.17   1.00]


Матрица U:
[   4.00  22.00  53.00  33.00]

[   0.00  -6.00 -18.50  -7.50]

[   0.00   0.00 -15.38  -8.62]

[   0.00   0.00   0.00  -0.10]




## 2.3*. Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [118]:
a = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])
(P, L, U) = la.lu(a)
print('LU разложение:\n')
print('Матрица L:')
printMatrix(L)
print('Матрица U:')
printMatrix(U)

LU разложение:

Матрица L:
[   1.00   0.00   0.00]

[   0.82   1.00   0.00]

[   0.18  -0.12   1.00]


Матрица U:
[  11.00   7.00   5.00]

[   0.00   2.27  -0.09]

[   0.00   0.00   2.08]




$Ly=b$, тогда: $\begin{cases}
y_1 = 1,\\ 
0.82y_1+y_2=-6,\\
0.18y_1 - 0.12y_2 + y_3 = -5
\end{cases} \Rightarrow \begin{cases}
y_1 = 1,\\
y_2 = -6.82, \\
y_3 = -5.9984
\end{cases}$

$Ux=y$, тогда $\begin{cases}
11x_1 + 7x_2 + 5x_3 = 1,\\
2.27x_2 - 0.09x_3=-6.82,\\
2.08x_3=-5,9984
\end{cases} \Rightarrow \begin{cases}
x_1 = 3.38,\\
x_2 = -3.12,\\
x_3 = -2.88
\end{cases}$

Переменные вычислены относительно (с учетом погрешности) правильно. Проверим:

In [121]:
y = linalg.solve(L, b)
y

array([ 1.        , -6.81818182, -6.        ])

In [123]:
x = linalg.solve(U, y)
x

array([ 3.38461538, -3.11538462, -2.88461538])

Вместе с тем, когда запускаем решение через библиотеку получаем совершенно иные решения:

In [124]:
linalg.solve(a, b)

array([-1.00000000e+00,  2.44249065e-16,  1.00000000e+00])

### <span style="color:red">Прошу подсказать в чем здесь ошибка</span>

## 2.4*. Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

### Решение:

$l_{11}=\sqrt{a_{11}} = \sqrt{81} = 9, \\
\displaystyle l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9} = -5, \\
\displaystyle l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9} = 5$

$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=5,\\
l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ( -15 - (-5)\cdot 5 \right )=2,\\
l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=3$

$L = \begin{pmatrix}
9 & 0 & 0\\
-5 & 5 & 0\\
5 & 2 & 3
\end{pmatrix}, L^T = \begin{pmatrix}
9 & -5 & 5\\
0 & 5 & 2\\
0 & 0 & 3
\end{pmatrix}$

$Ly=b, \Rightarrow \begin{cases}
9y_1 = 531,\\
-5y_1+5y_2=-460,\\
5y_3 +2y_2+3y_3=193
\end{cases}, \Rightarrow \begin{cases}
y_1=59,\\
y_2=-33,\\
y_3=-12
\end{cases}$

$L^Tx=y, \Rightarrow \begin{cases}
9x_1 - 5x_2 + 5x_3 = 59,\\
5x_2 + 2x_3 = -33,\\
3x_3 = -12
\end{cases}, \Rightarrow \begin{cases}
x_1 = 6,\\
x_2 = -5,\\
x_3 = -4
\end{cases}$

Проверяем:

In [130]:
A = np.array([[81, -45, 45],[-45, 50, -15],[45, -15, 38]])
b = np.array([531, -460, 193])
linalg.solve(A, b)

array([ 6., -5., -4.])

## 2.5*. Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.