In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# К признаку стажа добавим признаки: средняя стоимость занятия,
# квалификация репетитора
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2],
              [500, 700, 750, 600, 1450,
               800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2, 
               1, 3, 3, 1, 2]])

In [ ]:
X.T.shape

In [ ]:
y = [45, 55, 50, 59, 65,
    35, 75, 80, 50, 60]

In [ ]:
# Нормализация [0, 1]
X[2].min(), X[2].max()

In [ ]:
X_norm = X.copy()
X_norm = X_norm.astype(np.float64)
X_norm

In [ ]:
X_norm[1] = (X[1] - X[1].min()) / (X[1].max() - X[1].min())
X_norm

In [ ]:
X_norm[2] = (X[2] - X[2].min()) / (X[2].max() - X[2].min())
X_norm

In [ ]:
# Стандартизация

In [ ]:
plt.hist(X[1])

In [ ]:
plt.hist(X[2])

In [ ]:
X1_mean = X[1].mean()
X1_mean

In [ ]:
X1_std = X[1].std()
X1_std

In [ ]:
X_st = X.copy().astype(np.float64)

In [ ]:
X_st[1] = (X[1] - X1_mean) / X1_std
X_st

In [ ]:
np.mean(X_st[1]), np.std(X_st[1])

In [ ]:
plt.hist(X_st[1])

In [ ]:
def calc_std_feat(x):
    res = (x - x.mean()) / x.std()
    return res

In [ ]:
X_st[2] = calc_std_feat(X[2])

In [ ]:
X_st[3] = calc_std_feat(X[3])
X_st

In [ ]:
X_st

In [ ]:
from sklearn.preprocessing import StandardScaler # Стандартизация
from sklearn.preprocessing import MinMaxScaler # [0, 1]

In [ ]:
# SGD

In [64]:
# выбор объекта 
idx = np.random.randint(0, X.T.shape[0])
X.T[idx]

array([  1,   2, 750,   2])

In [65]:
def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2)
    return err

In [66]:
def eval_model(X, y, iterations, alpha=1e-4):
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        y_pred = np.dot(W, X)
        err = calc_mse(y, y_pred)
        W -= (alpha * (1/n * 2 * np.dot((y_pred - y), X.T)))
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [67]:
eval_model(X_st, y, iterations=1000, alpha=1e-2)

100 [49.7750889   4.14220322  3.38757036  4.06761614] 101.07452724575155
200 [56.38878768  4.53698984  3.08615769  4.02409403] 41.35089042889245
300 [57.26589347  4.84021435  2.81934646  3.99082705] 40.139564467842156
400 [57.38221485  5.08311643  2.59488818  3.97495103] 40.010819835015845
500 [57.39764134  5.27821659  2.40623646  3.9706991 ] 39.93635794314603
600 [57.3996872   5.43530491  2.24778409  3.9739371 ] 39.8862496944076
700 [57.39995852  5.56208733  2.11477516  3.98175843] 39.85221817075093
800 [57.3999945   5.6646451   2.00318286  3.99214733] 39.829001857976145
900 [57.39999927  5.74778981  1.90960281  4.00373067] 39.81310473747083
1000 [57.3999999   5.81533849  1.8311607   4.01559558] 39.80218514131114


array([57.3999999 ,  5.81533849,  1.8311607 ,  4.01559558])

In [69]:
def eval_sgd_model(X, y, iterations, qty_in_batch=1, alpha=1e-4):
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    n_batch = n // qty_in_batch
    if n % qty_in_batch != 0:
        n_batch += 1
    for i in range(1, iterations+1):
        for b in range(n_batch):
            start_ = qty_in_batch*b
            end_ = qty_in_batch*(b+1)

            # print(b, n_batch, start_, end_)

            X_tmp = X[:, start_ : end_]
            y_tmp = y[start_ : end_]
            y_pred_tmp = np.dot(W, X_tmp)
            err = calc_mse(y_tmp, y_pred_tmp)
            W -= (alpha * (1/n * 2 * np.dot((y_pred_tmp - y_tmp), X_tmp.T)))

    if i % (iterations / 10) == 0:
        print(i, W, err)
    return W

In [75]:
%whos

Variable          Type        Data/Info
---------------------------------------
MinMaxScaler      type        <class 'sklearn.preproces<...>sing._data.MinMaxScaler'>
StandardScaler    type        <class 'sklearn.preproces<...>ng._data.StandardScaler'>
X                 ndarray     4x10: 40 elems, type `int64`, 320 bytes
X1_mean           float64     2.6
X1_std            float64     2.8000000000000003
X_norm            ndarray     4x10: 40 elems, type `float64`, 320 bytes
X_st              ndarray     4x10: 40 elems, type `float64`, 320 bytes
calc_mse          function    <function calc_mse at 0x1a23941830>
calc_std_feat     function    <function calc_std_feat at 0x11f7e3290>
eval_model        function    <function eval_model at 0x1a239417a0>
eval_model_reg2   function    <function eval_model_reg2 at 0x11f569cb0>
eval_sgd_model    function    <function eval_sgd_model at 0x1a23389290>
idx               int         2
np                module      <module 'numpy' from '/Us<...>kages/numpy

In [78]:
X.T.shape

# batch_size = 2
# 0-2, 2-4, ..., 8-10 - 5 групп
# 1 эпоха

(10, 4)

In [73]:
eval_sgd_model(X_st, y, iterations=5000, qty_in_batch=64, alpha=1e-2)

5000 [57.4         6.12222595  1.42877139  4.11625073] 39.77774604853512


array([57.4       ,  6.12222595,  1.42877139,  4.11625073])

In [ ]:
# early_stopping
# задаем очень большое число эпозх -> 1e5
# n = 25, 50, 100, 

# 1000
# 200
# ...
# 0.01

In [79]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso, Ridge

In [81]:
Lasso().fit(X.T, y)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [82]:
Ridge().fit(X.T, y)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [ ]:
# L1 регуляризация - Lasso

f(x, W) + (lambda_/2) * np.sum(np.abs(W))

In [ ]:
# L2 регуляризация - Ridge

f(x, W) + (lambda_/2) * np.sum(W**2)

df/dw1 = d(w1**2 + w2**2 + w3**2) / dw1 = 2*w1 + 0 + 0 = 2*w1

In [ ]:
f'(x, W) + lambda_ * np.sum(W)

In [ ]:
def eval_model_reg2(X, y, iterations, alpha=1e-4, lambda_=1e-8):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        y_pred = np.dot(W, X)
        err = calc_mse(y, y_pred)
        W -= alpha * (1/n * 2 * np.dot((y_pred - y), X.T) + lambda_ * W) 
    if i % (iterations / 10) == 0:
        print(i, W, err)
    return W

In [ ]:
eval_model_reg2(X_st, y, iterations=5000, alpha=1e-2, lambda_=1e-4)

In [ ]:
# В некоторых алгоритмах используется обратный коэффициент
C = 1/lambda

In [83]:
X.T

array([[   1,    1,  500,    1],
       [   1,    1,  700,    1],
       [   1,    2,  750,    2],
       [   1,    1,  600,    1],
       [   1,    3, 1450,    2],
       [   1,    0,  800,    1],
       [   1,    5, 1500,    3],
       [   1,   10, 2000,    3],
       [   1,    1,  450,    1],
       [   1,    2, 1000,    2]])

In [84]:
y

[45, 55, 50, 59, 65, 35, 75, 80, 50, 60]

In [ ]:
# X -> X_train, X_valid
# 70/30, 80/20
# Кросс-валидация


# R2 = 0.75
# Доверительный интервал: [0.65, 0.85], [0.74, 0.76] 95%

In [ ]:
# X - конечная выборка
# Генеральная совокупность

# Пример: средняя зарплата в России
# Эксперимент 1: X
# Эксперименте 2: 1.1*x
# Эксперименте 3: 0.98*x

In [87]:
from sklearn.metrics import r2_score, mean_squared_error

In [91]:
y_true = [0, 1, 1, 0, 1]
y_pred = [10, 5, 2, 1, 0]

mean_squared_error(y_true, y_pred)

23.8

In [92]:
r2_score(y_true, y_pred)

-98.16666666666666

In [93]:
from sklearn.model_selection import KFold, StratifiedKFold, GroupKFold