# Author: Стурейко Игорь
## Project: Geekbrains.Mathematics
## Lesson 2 - Алгебра
## Date: 2020-06-06

## 1. Напишите уравнение параболы, проходящей через три точки (x,y): (1,2), (3,10), (5,1)

### Решение:
$\displaystyle 
\begin{matrix}
a + b + c = 2\\
9a + 3b + c = 10\\
25a + 5b + c = 1
\end{matrix}
$

In [11]:
import numpy as np
A = np.array([[1., 1., 1.], [9., 3., 1.], [25., 5., 1.]])
v = np.array([[2], [10], [1]])
np.linalg.det(A)
solv = np.linalg.solve(A, v)
v, A

(array([[ 2],
        [10],
        [ 1]]),
 array([[ 1.,  1.,  1.],
        [ 9.,  3.,  1.],
        [25.,  5.,  1.]]))

In [3]:
solv

array([[-2.125],
       [12.5  ],
       [-8.375]])

### $\displaystyle -2.125x^2+12.5x-8.375=y$

## 2. Решить задачу:
Известно, что свежий огурец на 99% состоит из воды. Месяц назад взвесили мешок со свежими огурцами. Получилось, что огурцов ровно 100 кг. Мешок убрали, а через месяц снова взвесили. Огурцы за это время усохли, и теперь вода составляет уже только 98% их веса. Сколько теперь (в кг) весят огурцы?

Огурцы составляли 1%, вода 99%, т.е $0.01+0.99=1$ теперь тоже количество воды составляет 98% при том же количестве огурцов $0.01 + 0.98(0.99)=0.9802$ т.е усохшие огурцы весят 98.02 кг.

## 3. Решить уравнения:

### 3.1 $2^x = 256$

$x = \log_2{256} = \log_2{2^8}=8$

### 3.2 $2^x=300$

$x = \log_2{300}=\log_22^2+\log_2{75}=2+\log_2{5^2 \cdot 3}=2(1+\log_25)+\log_23$

### 3.3 $\log_82^{8x-4}=4$

$\log_8{2^{(8x-4)}}=(8x-4)\log_8{2}=(8x-4)\log_{2^3}{2}=(8x-4)\frac{1}{3}\log_22=4 \Rightarrow 8x-4=12 \Rightarrow x = 2$

### 3.4 $3^{\log_9(5x-5)}=5$

$3^{\log_9{(5x-5)}}=(5x-5)\log_9{3}=\sqrt{5x-5}=5 \Rightarrow 5x-5=25 \Rightarrow x =6$

### 3.5 $x^{\log_3{(x+1)}}=9$

$x^{\log_3(x+1)}=(x+1)^{\log_3x}=3^{\log_33^2} \Rightarrow x =2$

## 4. Вычислить:

### 4.1 $\log_4{16}$

$\log_4{16}=\log_4{4^2}=2$

### 4.2 $\displaystyle \log_{5}\frac{1}{25}$

$\displaystyle \log_{5}\frac{1}{25}=\log_5{5^{-2}}=-2$

### 4.3 $\log_{25}{5}$

$\displaystyle \log_{25}{5}=\log_{5^2}5=\frac{1}{2}$

### 4.4 $\log_3{\sqrt{27}}$

$\displaystyle \log_3{\sqrt{27}}=\log_3{3^{\frac{3}{2}}}=\frac{3}{2}$

### 4.5 $\log_2{12}-\log_2{3}$

$\displaystyle \log_2{12}-\log_2{3} = \log_2{\frac{12}{3}}=\log_24=2$

### 4.5 $\log_6{12}+\log_6{3}$

$\log_6{12}+\log_6{3} = \log_6(12 \cdot 3) = \log_636 = \log_6{6^2}=2$

### 4.6 $e^{\ln5}$

$\displaystyle e^{\ln5}=5^{\ln e}=5$

### 4.7 $\displaystyle \frac{\log_2{225}}{\log_2{15}}$

$\displaystyle \frac{\log_2{225}}{\log_2{15}}=\frac{\log_2{15^2}}{\log_2{15}}=\frac{2\log_2{15}}{\log_2{15}}=2$

### 4.8 $\log_4{32}+\log_{0.1}{10}$

$\displaystyle \log_4{32}+\log_{0.1}{10} =\log_{2^2}{2^4}+\log_{10^{-1}}{10}=\frac{4}{2}+\frac{1}{(-1)}=1$

### 4.9 $9^{\log_3{\sqrt{5}}}$

$9^{\log_3{\sqrt{5}}}=\sqrt{5}^{\log_3{9}}=5$