In [1]:
!pwd

/Users/igor/Documents/Programming/Geekbrains/DataLibraries/Lesson_01_Numpy_Pandas


In [2]:
!ls -l

total 768
-rw-r--r--  1 igor  staff   80568 Jun 26 20:28 01_Numpy_calculations.ipynb
-rw-r--r--  1 igor  staff  138135 Jun 26 19:20 02_Work_with_Pandas.ipynb
-rw-r--r--  1 igor  staff   34556 Apr  7 11:13 Lesson_01_Numpy_Pandas_hTask.ipynb
-rw-r--r--  1 igor  staff      72 Jun 26 20:28 Untitled.ipynb
-rw-r--r--  1 igor  staff  129154 Apr  7 11:13 Webinar_02_training.ipynb


In [4]:
import numpy as np

In [38]:
a = [i for i in range(3)]
a

[0, 1, 2]

In [42]:
b = np.array(a*2)
b

array([0, 2, 4])

In [43]:
a = np.array(a)
a, b, a.shape, b.shape

(array([0, 1, 2]), array([0, 2, 4]), (3,), (3,))

In [44]:
c = a+b
c

array([0, 3, 6])

In [45]:
g = np.matrix(c)
g

matrix([[0, 3, 6]])

In [46]:
g.shape

(1, 3)

In [47]:
g.T

matrix([[0],
        [3],
        [6]])

In [48]:
np.dot(g, g.T)

matrix([[45]])

In [50]:
f = np.dot(g.T, g)
f

matrix([[ 0,  0,  0],
        [ 0,  9, 18],
        [ 0, 18, 36]])

In [51]:
np.trace(f)

45

In [59]:
f.diagonal()

matrix([[ 0,  9, 36]])

In [60]:
np.fliplr(f).diagonal()

matrix([[0, 9, 0]])

In [86]:
f = np.random.randint(0, 10, (5, 5))
f

array([[2, 6, 0, 9, 8],
       [6, 3, 8, 5, 5],
       [6, 6, 3, 2, 5],
       [6, 8, 2, 4, 4],
       [6, 8, 9, 4, 5]])

In [87]:
np.linalg.matrix_rank(f)

5

In [88]:
np.linalg.inv(f)

array([[-0.10049423,  0.18369028,  0.03995058,  0.19686985, -0.22034596],
       [ 0.00988468, -0.1738056 , -0.04901153,  0.06260297,  0.15691928],
       [-0.01482702,  0.0107084 , -0.0514827 , -0.09390445,  0.13962109],
       [ 0.03459638,  0.1416804 , -0.29654036,  0.21911038, -0.07578254],
       [ 0.10378913, -0.07495881,  0.36037891, -0.34266886,  0.02265239]])

## Работа с Pandas

In [89]:
import pandas as pd

In [90]:
a

array([0, 1, 2])

In [91]:
c

array([0, 3, 6])

### Series

In [93]:
a = pd.Series(a)

In [94]:
a

0    0
1    1
2    2
dtype: int64

In [95]:
a = pd.Series(np.random.randint(0,11,15))
a

0      4
1      4
2     10
3      9
4      7
5      3
6      6
7      4
8      0
9      2
10     4
11     3
12     0
13     1
14     0
dtype: int64

In [96]:
a[1]

4

In [97]:
a[a<3]

8     0
9     2
12    0
13    1
14    0
dtype: int64

In [101]:
a[a.index < 3]

0     4
1     4
2    10
dtype: int64

### DataFrame

In [115]:
year = [i for i in range(2020, 2010, -1)]*3
len(year)

30

In [116]:
val = [i for i in np.random.randint(0, 10, 30)]
len(val)

30

In [126]:
ind = [1]*10+[2]*10+[3]*10
len(ind)

30

In [127]:
df = pd.DataFrame({'Year':year,
                   'Val':val,
                   'Id':ind}, columns=['Year', 'Val', 'Id'])
df

Year  Val  Id
0   2020    6   1
1   2019    8   1
2   2018    5   1
3   2017    2   1
4   2016    5   1
5   2015    1   1
6   2014    6   1
7   2013    1   1
8   2012    6   1
9   2011    8   1
10  2020    9   2
11  2019    7   2
12  2018    5   2
13  2017    3   2
14  2016    0   2
15  2015    3   2
16  2014    9   2
17  2013    3   2
18  2012    2   2
19  2011    7   2
20  2020    6   3
21  2019    6   3
22  2018    2   3
23  2017    4   3
24  2016    6   3
25  2015    1   3
26  2014    7   3
27  2013    5   3
28  2012    9   3
29  2011    0   3

In [128]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    30 non-null     int64
 1   Val     30 non-null     int64
 2   Id      30 non-null     int64
dtypes: int64(3)
memory usage: 848.0 bytes


In [141]:
np.hstack((df.loc[df['Year']==2020,['Id', 'Val']].values, df.loc[df['Year']==2019,['Val']].values))

array([[1, 6, 8],
       [2, 9, 7],
       [3, 6, 6]])

In [164]:
df.loc[df['Year'].isin([2020, 2019]),['Id', 'Val']]

Id  Val
0    1    6
1    1    8
10   2    9
11   2    7
20   3    6
21   3    6

In [175]:
sum_val=pd.merge(df.loc[df['Year'].isin([2020]),['Id', 'Val']], df.loc[df['Year'].isin([2019]),['Id', 'Val']],on='Id',how='inner')
sum_val

Id  Val_x  Val_y
0   1      6      8
1   2      9      7
2   3      6      6

In [176]:
sum_val.rename(columns={'Val_x': '2020', 'Val_y': '2019'}, inplace=True)
sum_val

Id  2020  2019
0   1     6     8
1   2     9     7
2   3     6     6

In [177]:
sum_val=pd.merge(sum_val, df.loc[df['Year'].isin([2018]),['Id', 'Val']],on='Id',how='inner')
sum_val.rename(columns={'Val': '2018'}, inplace=True)
sum_val

Id  2020  2019  2018
0   1     6     8     5
1   2     9     7     5
2   3     6     6     2

In [210]:
def out_df(dataf: pd.DataFrame):
    sum_val=pd.merge(dataf.loc[dataf['Year'].isin([2011]),['Id', 'Val']], dataf.loc[dataf['Year'].isin([2012]),['Id', 'Val']],on='Id',how='inner')
    sum_val.rename(columns={'Val_x': '2011', 'Val_y': '2012'}, inplace=True)
    for i in np.flip(df['Year'].unique()[:-2]):
        sum_val=pd.merge(sum_val, df.loc[df['Year'] == i,['Id', 'Val']],on='Id',how='inner')
        sum_val.rename(columns={'Val': str(i)}, inplace=True)
    return sum_val

In [208]:
a = df['Year'].unique()[:-2]
a

array([2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013])

In [209]:
np.flip(a)

array([2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [180]:
str(a)

'20'

In [211]:
sum_val = out_df(df)
sum_val

Id  2011  2012  2013  2014  2015  2016  2017  2018  2019  2020
0   1     8     6     1     6     1     5     2     5     8     6
1   2     7     2     3     9     3     0     3     5     7     9
2   3     0     9     5     7     1     6     4     2     6     6